//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/19/2008 7:42:54 PM
namespace MVVM.Client.Data.DataServices
{
    
    /// <summary>
    /// There are no comments for GamesEntities in the schema.
    /// </summary>
    public partial class GamesEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new GamesEntities object.
        /// </summary>
        public GamesEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("GamesModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("MVVM.Client.Data.DataServices", typeName.Substring(10)), true);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("MVVM.Client.Data.DataServices", global::System.StringComparison.Ordinal))
            {
                return string.Concat("GamesModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Games in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Game> Games
        {
            get
            {
                if ((this._Games == null))
                {
                    this._Games = base.CreateQuery<Game>("Games");
                }
                return this._Games;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Game> _Games;
        /// <summary>
        /// There are no comments for Suppliers in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Supplier> Suppliers
        {
            get
            {
                if ((this._Suppliers == null))
                {
                    this._Suppliers = base.CreateQuery<Supplier>("Suppliers");
                }
                return this._Suppliers;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Supplier> _Suppliers;
        /// <summary>
        /// There are no comments for Games in the schema.
        /// </summary>
        public void AddToGames(Game game)
        {
            base.AddObject("Games", game);
        }
        /// <summary>
        /// There are no comments for Suppliers in the schema.
        /// </summary>
        public void AddToSuppliers(Supplier supplier)
        {
            base.AddObject("Suppliers", supplier);
        }
    }
    /// <summary>
    /// There are no comments for GamesModel.Game in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProductID")]
    public partial class Game
    {
        /// <summary>
        /// Create a new Game object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="productName">Initial value of ProductName.</param>
        /// <param name="productDescription">Initial value of ProductDescription.</param>
        /// <param name="listPrice">Initial value of ListPrice.</param>
        /// <param name="productTypeID">Initial value of ProductTypeID.</param>
        /// <param name="listPriceCurrency">Initial value of ListPriceCurrency.</param>
        /// <param name="systemName">Initial value of SystemName.</param>
        public static Game CreateGame(int productID, string productName, string productDescription, double listPrice, int productTypeID, string listPriceCurrency, string systemName)
        {
            Game game = new Game();
            game.ProductID = productID;
            game.ProductName = productName;
            game.ProductDescription = productDescription;
            game.ListPrice = listPrice;
            game.ProductTypeID = productTypeID;
            game.ListPriceCurrency = listPriceCurrency;
            game.SystemName = systemName;
            return game;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this._ProductID = value;
                this.OnProductIDChanged();
            }
        }
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this._ProductName = value;
                this.OnProductNameChanged();
            }
        }
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property ProductDescription in the schema.
        /// </summary>
        public string ProductDescription
        {
            get
            {
                return this._ProductDescription;
            }
            set
            {
                this.OnProductDescriptionChanging(value);
                this._ProductDescription = value;
                this.OnProductDescriptionChanged();
            }
        }
        private string _ProductDescription;
        partial void OnProductDescriptionChanging(string value);
        partial void OnProductDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ListPrice in the schema.
        /// </summary>
        public double ListPrice
        {
            get
            {
                return this._ListPrice;
            }
            set
            {
                this.OnListPriceChanging(value);
                this._ListPrice = value;
                this.OnListPriceChanged();
            }
        }
        private double _ListPrice;
        partial void OnListPriceChanging(double value);
        partial void OnListPriceChanged();
        /// <summary>
        /// There are no comments for Property ProductTypeID in the schema.
        /// </summary>
        public int ProductTypeID
        {
            get
            {
                return this._ProductTypeID;
            }
            set
            {
                this.OnProductTypeIDChanging(value);
                this._ProductTypeID = value;
                this.OnProductTypeIDChanged();
            }
        }
        private int _ProductTypeID;
        partial void OnProductTypeIDChanging(int value);
        partial void OnProductTypeIDChanged();
        /// <summary>
        /// There are no comments for Property ReleaseDate in the schema.
        /// </summary>
        public global::System.Nullable<global::System.DateTime> ReleaseDate
        {
            get
            {
                return this._ReleaseDate;
            }
            set
            {
                this.OnReleaseDateChanging(value);
                this._ReleaseDate = value;
                this.OnReleaseDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ReleaseDate;
        partial void OnReleaseDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnReleaseDateChanged();
        /// <summary>
        /// There are no comments for Property ProductImageUrl in the schema.
        /// </summary>
        public string ProductImageUrl
        {
            get
            {
                return this._ProductImageUrl;
            }
            set
            {
                this.OnProductImageUrlChanging(value);
                this._ProductImageUrl = value;
                this.OnProductImageUrlChanged();
            }
        }
        private string _ProductImageUrl;
        partial void OnProductImageUrlChanging(string value);
        partial void OnProductImageUrlChanged();
        /// <summary>
        /// There are no comments for Property ListPriceCurrency in the schema.
        /// </summary>
        public string ListPriceCurrency
        {
            get
            {
                return this._ListPriceCurrency;
            }
            set
            {
                this.OnListPriceCurrencyChanging(value);
                this._ListPriceCurrency = value;
                this.OnListPriceCurrencyChanged();
            }
        }
        private string _ListPriceCurrency;
        partial void OnListPriceCurrencyChanging(string value);
        partial void OnListPriceCurrencyChanged();
        /// <summary>
        /// There are no comments for Property SystemName in the schema.
        /// </summary>
        public string SystemName
        {
            get
            {
                return this._SystemName;
            }
            set
            {
                this.OnSystemNameChanging(value);
                this._SystemName = value;
                this.OnSystemNameChanged();
            }
        }
        private string _SystemName;
        partial void OnSystemNameChanging(string value);
        partial void OnSystemNameChanged();
        /// <summary>
        /// There are no comments for Property Rating in the schema.
        /// </summary>
        public string Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
                this.OnRatingChanging(value);
                this._Rating = value;
                this.OnRatingChanged();
            }
        }
        private string _Rating;
        partial void OnRatingChanging(string value);
        partial void OnRatingChanged();
        /// <summary>
        /// There are no comments for Property Genre in the schema.
        /// </summary>
        public string Genre
        {
            get
            {
                return this._Genre;
            }
            set
            {
                this.OnGenreChanging(value);
                this._Genre = value;
                this.OnGenreChanged();
            }
        }
        private string _Genre;
        partial void OnGenreChanging(string value);
        partial void OnGenreChanged();
        /// <summary>
        /// There are no comments for Property Publisher in the schema.
        /// </summary>
        public string Publisher
        {
            get
            {
                return this._Publisher;
            }
            set
            {
                this.OnPublisherChanging(value);
                this._Publisher = value;
                this.OnPublisherChanged();
            }
        }
        private string _Publisher;
        partial void OnPublisherChanging(string value);
        partial void OnPublisherChanged();
        /// <summary>
        /// There are no comments for Property Developer in the schema.
        /// </summary>
        public string Developer
        {
            get
            {
                return this._Developer;
            }
            set
            {
                this.OnDeveloperChanging(value);
                this._Developer = value;
                this.OnDeveloperChanged();
            }
        }
        private string _Developer;
        partial void OnDeveloperChanging(string value);
        partial void OnDeveloperChanged();
        /// <summary>
        /// There are no comments for Property RatingUrl in the schema.
        /// </summary>
        public string RatingUrl
        {
            get
            {
                return this._RatingUrl;
            }
            set
            {
                this.OnRatingUrlChanging(value);
                this._RatingUrl = value;
                this.OnRatingUrlChanged();
            }
        }
        private string _RatingUrl;
        partial void OnRatingUrlChanging(string value);
        partial void OnRatingUrlChanged();
        /// <summary>
        /// There are no comments for Property PlayerInfo in the schema.
        /// </summary>
        public string PlayerInfo
        {
            get
            {
                return this._PlayerInfo;
            }
            set
            {
                this.OnPlayerInfoChanging(value);
                this._PlayerInfo = value;
                this.OnPlayerInfoChanged();
            }
        }
        private string _PlayerInfo;
        partial void OnPlayerInfoChanging(string value);
        partial void OnPlayerInfoChanged();
        /// <summary>
        /// There are no comments for Supplier in the schema.
        /// </summary>
        public Supplier Supplier
        {
            get
            {
                return this._Supplier;
            }
            set
            {
                this._Supplier = value;
            }
        }
        private Supplier _Supplier;
    }
    /// <summary>
    /// There are no comments for GamesModel.Supplier in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SupplierID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SupplierID")]
    public partial class Supplier
    {
        /// <summary>
        /// Create a new Supplier object.
        /// </summary>
        /// <param name="supplierID">Initial value of SupplierID.</param>
        /// <param name="supplierName">Initial value of SupplierName.</param>
        public static Supplier CreateSupplier(int supplierID, string supplierName)
        {
            Supplier supplier = new Supplier();
            supplier.SupplierID = supplierID;
            supplier.SupplierName = supplierName;
            return supplier;
        }
        /// <summary>
        /// There are no comments for Property SupplierID in the schema.
        /// </summary>
        public int SupplierID
        {
            get
            {
                return this._SupplierID;
            }
            set
            {
                this.OnSupplierIDChanging(value);
                this._SupplierID = value;
                this.OnSupplierIDChanged();
            }
        }
        private int _SupplierID;
        partial void OnSupplierIDChanging(int value);
        partial void OnSupplierIDChanged();
        /// <summary>
        /// There are no comments for Property SupplierName in the schema.
        /// </summary>
        public string SupplierName
        {
            get
            {
                return this._SupplierName;
            }
            set
            {
                this.OnSupplierNameChanging(value);
                this._SupplierName = value;
                this.OnSupplierNameChanged();
            }
        }
        private string _SupplierName;
        partial void OnSupplierNameChanging(string value);
        partial void OnSupplierNameChanged();
        /// <summary>
        /// There are no comments for Property SupplierAddress in the schema.
        /// </summary>
        public string SupplierAddress
        {
            get
            {
                return this._SupplierAddress;
            }
            set
            {
                this.OnSupplierAddressChanging(value);
                this._SupplierAddress = value;
                this.OnSupplierAddressChanged();
            }
        }
        private string _SupplierAddress;
        partial void OnSupplierAddressChanging(string value);
        partial void OnSupplierAddressChanged();
        /// <summary>
        /// There are no comments for Property SupplierPhone in the schema.
        /// </summary>
        public string SupplierPhone
        {
            get
            {
                return this._SupplierPhone;
            }
            set
            {
                this.OnSupplierPhoneChanging(value);
                this._SupplierPhone = value;
                this.OnSupplierPhoneChanged();
            }
        }
        private string _SupplierPhone;
        partial void OnSupplierPhoneChanging(string value);
        partial void OnSupplierPhoneChanged();
        /// <summary>
        /// There are no comments for Games in the schema.
        /// </summary>
        public global::System.Collections.ObjectModel.Collection<Game> Games
        {
            get
            {
                return this._Games;
            }
            set
            {
                if ((value != null))
                {
                    this._Games = value;
                }
            }
        }
        private global::System.Collections.ObjectModel.Collection<Game> _Games = new global::System.Collections.ObjectModel.Collection<Game>();
    }
}
