//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GamesModel", "FK_Product_Supplier", "Supplier", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MVVM.Data.Supplier), "Product", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MVVM.Data.Game))]

// Original file name:
// Generation date: 12/19/2008 7:40:50 PM
namespace MVVM.Data
{
    
    /// <summary>
    /// There are no comments for GamesEntities in the schema.
    /// </summary>
    public partial class GamesEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new GamesEntities object using the connection string found in the 'GamesEntities' section of the application configuration file.
        /// </summary>
        public GamesEntities() : 
                base("name=GamesEntities", "GamesEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GamesEntities object.
        /// </summary>
        public GamesEntities(string connectionString) : 
                base(connectionString, "GamesEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GamesEntities object.
        /// </summary>
        public GamesEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "GamesEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Games in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Game> Games
        {
            get
            {
                if ((this._Games == null))
                {
                    this._Games = base.CreateQuery<Game>("[Games]");
                }
                return this._Games;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Game> _Games;
        /// <summary>
        /// There are no comments for Suppliers in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Supplier> Suppliers
        {
            get
            {
                if ((this._Suppliers == null))
                {
                    this._Suppliers = base.CreateQuery<Supplier>("[Suppliers]");
                }
                return this._Suppliers;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Supplier> _Suppliers;
        /// <summary>
        /// There are no comments for Games in the schema.
        /// </summary>
        public void AddToGames(Game game)
        {
            base.AddObject("Games", game);
        }
        /// <summary>
        /// There are no comments for Suppliers in the schema.
        /// </summary>
        public void AddToSuppliers(Supplier supplier)
        {
            base.AddObject("Suppliers", supplier);
        }
    }
    /// <summary>
    /// There are no comments for GamesModel.Game in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GamesModel", Name="Game")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Game : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Game object.
        /// </summary>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="productName">Initial value of ProductName.</param>
        /// <param name="productDescription">Initial value of ProductDescription.</param>
        /// <param name="listPrice">Initial value of ListPrice.</param>
        /// <param name="productTypeID">Initial value of ProductTypeID.</param>
        /// <param name="listPriceCurrency">Initial value of ListPriceCurrency.</param>
        /// <param name="systemName">Initial value of SystemName.</param>
        public static Game CreateGame(int productID, string productName, string productDescription, double listPrice, int productTypeID, string listPriceCurrency, string systemName)
        {
            Game game = new Game();
            game.ProductID = productID;
            game.ProductName = productName;
            game.ProductDescription = productDescription;
            game.ListPrice = listPrice;
            game.ProductTypeID = productTypeID;
            game.ListPriceCurrency = listPriceCurrency;
            game.SystemName = systemName;
            return game;
        }
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this.ReportPropertyChanging("ProductID");
                this._ProductID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductID");
                this.OnProductIDChanged();
            }
        }
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this.ReportPropertyChanging("ProductName");
                this._ProductName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductName");
                this.OnProductNameChanged();
            }
        }
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property ProductDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDescription
        {
            get
            {
                return this._ProductDescription;
            }
            set
            {
                this.OnProductDescriptionChanging(value);
                this.ReportPropertyChanging("ProductDescription");
                this._ProductDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProductDescription");
                this.OnProductDescriptionChanged();
            }
        }
        private string _ProductDescription;
        partial void OnProductDescriptionChanging(string value);
        partial void OnProductDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ListPrice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double ListPrice
        {
            get
            {
                return this._ListPrice;
            }
            set
            {
                this.OnListPriceChanging(value);
                this.ReportPropertyChanging("ListPrice");
                this._ListPrice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ListPrice");
                this.OnListPriceChanged();
            }
        }
        private double _ListPrice;
        partial void OnListPriceChanging(double value);
        partial void OnListPriceChanged();
        /// <summary>
        /// There are no comments for Property ProductTypeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductTypeID
        {
            get
            {
                return this._ProductTypeID;
            }
            set
            {
                this.OnProductTypeIDChanging(value);
                this.ReportPropertyChanging("ProductTypeID");
                this._ProductTypeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProductTypeID");
                this.OnProductTypeIDChanged();
            }
        }
        private int _ProductTypeID;
        partial void OnProductTypeIDChanging(int value);
        partial void OnProductTypeIDChanged();
        /// <summary>
        /// There are no comments for Property ReleaseDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ReleaseDate
        {
            get
            {
                return this._ReleaseDate;
            }
            set
            {
                this.OnReleaseDateChanging(value);
                this.ReportPropertyChanging("ReleaseDate");
                this._ReleaseDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ReleaseDate");
                this.OnReleaseDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ReleaseDate;
        partial void OnReleaseDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnReleaseDateChanged();
        /// <summary>
        /// There are no comments for Property ProductImageUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImageUrl
        {
            get
            {
                return this._ProductImageUrl;
            }
            set
            {
                this.OnProductImageUrlChanging(value);
                this.ReportPropertyChanging("ProductImageUrl");
                this._ProductImageUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ProductImageUrl");
                this.OnProductImageUrlChanged();
            }
        }
        private string _ProductImageUrl;
        partial void OnProductImageUrlChanging(string value);
        partial void OnProductImageUrlChanged();
        /// <summary>
        /// There are no comments for Property ListPriceCurrency in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ListPriceCurrency
        {
            get
            {
                return this._ListPriceCurrency;
            }
            set
            {
                this.OnListPriceCurrencyChanging(value);
                this.ReportPropertyChanging("ListPriceCurrency");
                this._ListPriceCurrency = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ListPriceCurrency");
                this.OnListPriceCurrencyChanged();
            }
        }
        private string _ListPriceCurrency;
        partial void OnListPriceCurrencyChanging(string value);
        partial void OnListPriceCurrencyChanged();
        /// <summary>
        /// There are no comments for Property SystemName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemName
        {
            get
            {
                return this._SystemName;
            }
            set
            {
                this.OnSystemNameChanging(value);
                this.ReportPropertyChanging("SystemName");
                this._SystemName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SystemName");
                this.OnSystemNameChanged();
            }
        }
        private string _SystemName;
        partial void OnSystemNameChanging(string value);
        partial void OnSystemNameChanged();
        /// <summary>
        /// There are no comments for Property Rating in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
                this.OnRatingChanging(value);
                this.ReportPropertyChanging("Rating");
                this._Rating = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Rating");
                this.OnRatingChanged();
            }
        }
        private string _Rating;
        partial void OnRatingChanging(string value);
        partial void OnRatingChanged();
        /// <summary>
        /// There are no comments for Property Genre in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre
        {
            get
            {
                return this._Genre;
            }
            set
            {
                this.OnGenreChanging(value);
                this.ReportPropertyChanging("Genre");
                this._Genre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Genre");
                this.OnGenreChanged();
            }
        }
        private string _Genre;
        partial void OnGenreChanging(string value);
        partial void OnGenreChanged();
        /// <summary>
        /// There are no comments for Property Publisher in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher
        {
            get
            {
                return this._Publisher;
            }
            set
            {
                this.OnPublisherChanging(value);
                this.ReportPropertyChanging("Publisher");
                this._Publisher = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Publisher");
                this.OnPublisherChanged();
            }
        }
        private string _Publisher;
        partial void OnPublisherChanging(string value);
        partial void OnPublisherChanged();
        /// <summary>
        /// There are no comments for Property Developer in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Developer
        {
            get
            {
                return this._Developer;
            }
            set
            {
                this.OnDeveloperChanging(value);
                this.ReportPropertyChanging("Developer");
                this._Developer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Developer");
                this.OnDeveloperChanged();
            }
        }
        private string _Developer;
        partial void OnDeveloperChanging(string value);
        partial void OnDeveloperChanged();
        /// <summary>
        /// There are no comments for Property RatingUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingUrl
        {
            get
            {
                return this._RatingUrl;
            }
            set
            {
                this.OnRatingUrlChanging(value);
                this.ReportPropertyChanging("RatingUrl");
                this._RatingUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RatingUrl");
                this.OnRatingUrlChanged();
            }
        }
        private string _RatingUrl;
        partial void OnRatingUrlChanging(string value);
        partial void OnRatingUrlChanged();
        /// <summary>
        /// There are no comments for Property PlayerInfo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerInfo
        {
            get
            {
                return this._PlayerInfo;
            }
            set
            {
                this.OnPlayerInfoChanging(value);
                this.ReportPropertyChanging("PlayerInfo");
                this._PlayerInfo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PlayerInfo");
                this.OnPlayerInfoChanged();
            }
        }
        private string _PlayerInfo;
        partial void OnPlayerInfoChanging(string value);
        partial void OnPlayerInfoChanged();
        /// <summary>
        /// There are no comments for Supplier in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GamesModel", "FK_Product_Supplier", "Supplier")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Supplier Supplier
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Supplier>("GamesModel.FK_Product_Supplier", "Supplier").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Supplier>("GamesModel.FK_Product_Supplier", "Supplier").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Supplier in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Supplier> SupplierReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Supplier>("GamesModel.FK_Product_Supplier", "Supplier");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Supplier>("GamesModel.FK_Product_Supplier", "Supplier", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GamesModel.Supplier in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SupplierID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GamesModel", Name="Supplier")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Supplier : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Supplier object.
        /// </summary>
        /// <param name="supplierID">Initial value of SupplierID.</param>
        /// <param name="supplierName">Initial value of SupplierName.</param>
        public static Supplier CreateSupplier(int supplierID, string supplierName)
        {
            Supplier supplier = new Supplier();
            supplier.SupplierID = supplierID;
            supplier.SupplierName = supplierName;
            return supplier;
        }
        /// <summary>
        /// There are no comments for Property SupplierID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierID
        {
            get
            {
                return this._SupplierID;
            }
            set
            {
                this.OnSupplierIDChanging(value);
                this.ReportPropertyChanging("SupplierID");
                this._SupplierID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SupplierID");
                this.OnSupplierIDChanged();
            }
        }
        private int _SupplierID;
        partial void OnSupplierIDChanging(int value);
        partial void OnSupplierIDChanged();
        /// <summary>
        /// There are no comments for Property SupplierName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName
        {
            get
            {
                return this._SupplierName;
            }
            set
            {
                this.OnSupplierNameChanging(value);
                this.ReportPropertyChanging("SupplierName");
                this._SupplierName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SupplierName");
                this.OnSupplierNameChanged();
            }
        }
        private string _SupplierName;
        partial void OnSupplierNameChanging(string value);
        partial void OnSupplierNameChanged();
        /// <summary>
        /// There are no comments for Property SupplierAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierAddress
        {
            get
            {
                return this._SupplierAddress;
            }
            set
            {
                this.OnSupplierAddressChanging(value);
                this.ReportPropertyChanging("SupplierAddress");
                this._SupplierAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SupplierAddress");
                this.OnSupplierAddressChanged();
            }
        }
        private string _SupplierAddress;
        partial void OnSupplierAddressChanging(string value);
        partial void OnSupplierAddressChanged();
        /// <summary>
        /// There are no comments for Property SupplierPhone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierPhone
        {
            get
            {
                return this._SupplierPhone;
            }
            set
            {
                this.OnSupplierPhoneChanging(value);
                this.ReportPropertyChanging("SupplierPhone");
                this._SupplierPhone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SupplierPhone");
                this.OnSupplierPhoneChanged();
            }
        }
        private string _SupplierPhone;
        partial void OnSupplierPhoneChanging(string value);
        partial void OnSupplierPhoneChanged();
        /// <summary>
        /// There are no comments for Games in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GamesModel", "FK_Product_Supplier", "Product")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Game> Games
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Game>("GamesModel.FK_Product_Supplier", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Game>("GamesModel.FK_Product_Supplier", "Product", value);
                }
            }
        }
    }
}
